---
prometheus::server::scrape_configs:
  - job_name: prometheus
    scrape_interval: '10s'
    scrape_timeout: '5s'
    static_configs:
      - targets:
        - 'localhost:9090'
  - job_name: node
    scrape_interval: '10s'
    scrape_timeout: '5s'
    static_configs:
      - targets:
        - 'localhost:9100'
        - 'grafana.openrepose.org:9100'
        - 'redirects.openrepose.org:9100'
        - 'influxdb.openrepose.org:9100'
        - 'puppet.openrepose.org:9100'
        - 'phone-home.openrepose.org:9100'
        - 'jenkins.openrepose.org:9100'
        - 'build-slave-01.openrepose.org:9100'
        - 'build-slave-02.openrepose.org:9100'
        - 'build-slave-03.openrepose.org:9100'
        - 'build-slave-04.openrepose.org:9100'
        - 'build-slave-05.openrepose.org:9100'
        - 'build-slave-06.openrepose.org:9100'
        - 'build-slave-07.openrepose.org:9100'
        - 'build-slave-08.openrepose.org:9100'
        - 'build-slave-09.openrepose.org:9100'
        - 'build-slave-10.openrepose.org:9100'
        - 'intense-slave-01.openrepose.org:9100'
        - 'intense-slave-02.openrepose.org:9100'
        - 'performance-slave-01.openrepose.org:9100'
        - 'performance-slave-02.openrepose.org:9100'
        - 'performance-slave-03.openrepose.org:9100'
        - 'legacy-slave-01.openrepose.org:9100'
  - job_name: blackbox
    scrape_interval: '60s'
    scrape_timeout: '5s'
    metrics_path: '/probe'
    params:
      module: ['http_2xx']
    static_configs:
      - targets:
        - 'https://prometheus.openrepose.org'
        - 'https://jenkins.openrepose.org'
    relabel_configs:
      - source_labels: ['__address__']
        target_label: '__param_target'
      - source_labels: ['__param_target']
        target_label: 'instance'
      - replacement: 'localhost:9115'
        target_label: '__address__'

prometheus::server::alerts:
  groups:
    - name: 'alert.rules'
      rules:
        - alert: 'InstanceDown'
          expr: 'up == 0'
          for: '5m'
          labels:
            severity: 'critical'
          annotations:
            summary: 'Instance {{ $labels.instance }} down'
            description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
        - alert: 'PackagesOutdated'
          expr: 'apt_upgrades_pending > 0'
          for: '15m'
          labels:
            severity: 'warning'
          annotations:
            summary: 'Instance {{ $labels.instance }} has outdated packages installed'
            description: '{{ $labels.instance }} of job {{ $labels.job }} has had outdated packages for more than 15 minutes.'
        - alert: 'PuppetAgentDown'
          expr: 'node_systemd_unit_state{name="puppet.service",state="active"} == 0'
          for: '5m'
          labels:
            severity: 'warning'
          annotations:
            summary: 'Instance {{ $labels.instance }} is not running a Puppet agent'
            description: '{{ $labels.instance }} of job {{ $labels.job }} has not been running a Puppet agent for more than 5 minutes.'
        - alert: 'NodeExporterDown'
          expr: 'node_systemd_unit_state{name="node_exporter.service",state="active"} == 0'
          for: '5m'
          labels:
            severity: 'warning'
          annotations:
            summary: 'Instance {{ $labels.instance }} is not running a Node exporter'
            description: '{{ $labels.instance }} of job {{ $labels.job }} has not been running a Node exporter for more than 5 minutes.'
        - alert: 'RackspaceMonitoringDown'
          expr: 'node_systemd_unit_state{name="rackspace-monitoring-agent.service",state="active"} == 0'
          for: '5m'
          labels:
            severity: 'warning'
          annotations:
            summary: 'Instance {{ $labels.instance }} is not running Rackspace monitoring'
            description: '{{ $labels.instance }} of job {{ $labels.job }} has not been running Rackspace monitoring for more than 5 minutes.'
        - alert: 'HighCpuUsage'
          expr: '(100 - (avg by (instance) (irate(node_cpu_seconds_total{job="node",mode="idle"}[5m])) * 100)) >= 85'
          for: '5m'
          labels:
            severity: 'warning'
          annotations:
            summary: 'Instance {{ $labels.instance }} has high CPU usage'
            description: '{{ $labels.instance }} has high CPU usage.'
        - alert: 'LowMemory'
          expr: 'round(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100) <= 20'
          for: '5m'
          labels:
            severity: 'warning'
          annotations:
            summary: 'Instance {{ $labels.instance }} is low on available memory'
            description: '{{ $labels.instance }} of job {{ $labels.job }} has {{ $value }}% available memory.'
        - alert: 'LowDiskSpace'
          expr: 'round(node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"} * 100) <= 20'
          for: '5m'
          labels:
            severity: 'warning'
          annotations:
            summary: 'Instance {{ $labels.instance }} is low on disk space'
            description: '{{ $labels.instance }} of job {{ $labels.job }} has {{ $value }}% free disk space.'
        - alert: 'SslCertExpiring'
          expr: 'probe_ssl_earliest_cert_expiry - time() < 86400 * 30'
          for: '5m'
          labels:
            severity: 'warning'
          annotations:
            summary: 'Instance {{ $labels.instance }} has an expiring SSL certificate'
            description: '{{ $labels.instance }} has an SSL certificate expiring soon.'
        # TODO: Jenkins slave process
        # TODO: SSH over IPv4 and IPv6
